[project]
name = "mambler"
version = "0.1.0"
description = "Converts Markdown into Ancient Machine Book (AMB) format."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "md2txt",
]

[tool.uv.sources]
md2txt = { git = "https://github.com/randogoth/md2txt", rev = "master" }
